In [17]:
import pandas as pd
import numpy as np

pd.MultiIndex.from_tuples([('basic', 'id'), ('basic', 'id_validator'), ('basic', 'price'), ('spec', 'core'), ('spec', 'clock')])
df = pd.DataFrame(columns=['id', 'id_validator'], data=np.random.randn(3, 2))
df.set_index('id', inplace=True)

print(df)
df.columns = pd.MultiIndex.from_product([['basic'], df.columns])
a = df.iloc[2].name

for k, v in df.loc[df[('basic', 'id_validator')] < 0].iterrows():
    df.loc[k, ('basic', 'price')] = 30

print(df)

           id_validator
id
-0.511583     -0.661708
-0.932668     -0.903897
-2.049364      0.705903
                 basic
          id_validator price
id
-0.511583    -0.661708  30.0
-0.932668    -0.903897  30.0
-2.049364     0.705903   NaN

In [100]:
df = pd.DataFrame(columns=['id', 'id_validator'], data=np.random.randn(3, 2))
df.loc[2, 'a'] = 1
print(df)
a = df.loc[1, 'a']
print(a)
print(type(a))
b = np.float64(np.NaN)
print(b)
print(type(b))
print(np.isnan(b))
print(a is a)

         id  id_validator    a
0  0.648842     -0.449623  NaN
1  0.449134     -0.570764  NaN
2  0.006789     -1.118616  1.0
nan
<class 'numpy.float64'>
nan
<class 'numpy.float64'>
True
True

In [106]:
df = pd.read_pickle(f'SSD_review.pkl')
df

,id,sentence,time,good,bad
0,13190630,명정보를 통해 2TB 제품을 구매했습니다. 일단 테스트 해봐야겠네요.,2021.02.02. 11:02:51,,1
1,13190630,올라왔구나. 그래서 얼마냐?,2021.01.21. 09:31:32,,1
2,13190630,진짜 짜증난다.\n아래 글에 첨부된 샷을 보면 알겠지만 여지것 TBW 4.6TB 밖...,2022.07.02. 15:11:18,,
3,13190630,기존 사용하던 2TB SSD가 사망하고 새로 구입한 870EVO 2TB 오래 오래 ...,2022.07.02. 15:04:16,,
4,13190630,"이 제품 정말 최악 입니다.\nPC방 게임 서버에 다수를 사용 중인데, 1년 이내에...",2022.06.12. 17:35:24,,
5,13190573,m.2 슬롯에 꼽는 제품의 문제점은 대부분 1개 밖에 장착할 수 없다는 것입니다. ...,2022.07.12. 10:47:41,,
6,13190573,아... 구매한지 1년안됬는데... 작년 가을에 배드색터로 새상품 교체 받았습니다....,2022.02.08. 14:24:07,,
7,13190573,이제보니 동일한 가격으로 nvme방식 살수있던데 sata를 내가 산 흑우였구나,2021.11.26. 14:36:18,4,
8,13190573,SSD 1테라 가격은 10 만원 이하로 떨어져야 한다..M.2 SSD 가격은 그렇다...,2021.09.17. 14:45:55,3,
9,13190573,여기보다 쿠팡이 싸네요,2021.09.13. 16:29:45,4,
10,13190573,159000,2021.07.08. 20:55:31,,
11,13190573,163360,2021.06.09. 01:31:22,,
12,13190573,166250,2021.05.27. 01:25:02,,
13,13190573,175500,2021.05.09. 01:28:13,,
14,13190573,SSD 1테라 가격은 10 만원 이하로 떨어져야 한다..M.2 SSD 가격은 그렇다...,2021.02.18. 07:00:43,NaN,NaN
15,13190573,빅스마일데이 행사중 http://item.gmarket.co.kr/Item?good...,2021.02.16. 13:44:56,NaN,NaN
16,13190573,970evo 1테라가 이거랑 만원도 차이안나는데 이거 살빠에 970evo 1테라 살둣,2021.02.11. 00:33:35,,3
17,13190573,970evo 1테라가 이거랑 만원도 차이안나는데 이거 살빠에 970evo 1테라 살둣,2021.02.11. 00:33:35,NaN,NaN
18,13190573,기대 돼네요..,2021.01.31. 16:23:25,,
19,13190573,사타를 이 가격에 파는 건 좀....,2021.01.26. 14:42:37,2,1
20,13190573,870 evo...램...탑재는 DDR4 라서 좋긴 허네..근데 가격이 좀 세다,2021.01.24. 17:14:38,,
21,13190573,비싸죠. 860 evo 재고 좀 털어내고 그 자리로 들어갈 듯.,2021.01.22. 21:52:20,,
22,13190573,외장하드랑 경쟁하기엔 가격이 많이 아쉬운듯...\n속도를 원하면 X5사면 되고 용량...,2021.01.21. 16:44:13,NaN,NaN
23,13190573,PRO는 이제 더이상 출시 안하는 건가? EVO만 나오네.,2021.01.21. 04:42:19,1,
24,13190573,비싸구나... 내돈 주고는 못사겠다.,2021.01.21. 02:54:14,,
25,13190573,가격도 그렇고 포지션이 애매함 메인은 m2 쓰고 서브로 대부분 쓸껀데 860대비 1...,2021.01.20. 22:08:02,,2
26,13190573,빅스라서 샀는데 신세계입니다 ㅎㅎ,2022.05.22. 11:14:35,,
27,13190573,40대 중반 아저씨입니다. 집에 19살 딸래미 용량부족하다고 (게임설치) 해서 c드...,2022.04.26. 09:22:08,NaN,NaN
28,13190573,870EVO 1TB 제품이 확실히 전 세대보다 소비전력이 조금 개선됐는지\n온도가 ...,2022.02.01. 14:29:30,,
29,13190573,2월 빅스마일 1테라 11만원 아주 잘산듯\n..,2021.03.27. 18:35:05,1,
30,13190573,860 870 두 제품 사용하는데요 번갈아가며 윈도우10 설치해서 실 체감 느껴보니...,2021.01.26. 15:20:18,2,2

In [129]:
df = pd.DataFrame(np.random.randn(3, 3), columns=list('ABC'))
df.set_index('A', inplace=True)
print(df)
# df.to_hdf('test.h5', 'bbb')
df = pd.read_hdf('test.h5', 'bbb')
print(df)

                  B         C
A
 0.951513  0.058953 -0.207132
 0.372932  0.995785 -0.832741
-0.818930 -0.790585  0.985096
                 B         C
A
1.117549  0.097771 -0.364268
1.173383  0.093490  1.596162
1.057982  2.737164  1.798586

In [156]:
import numpy as np
def get_hdf_keys(dir):
    with pd.HDFStore(dir) as store:
        return [e[1:] for e in store.keys()]

dir = 'danawa_crawling_data.h5'
print(get_hdf_keys(dir))
df = pd.read_hdf(dir, 'SSD_detail')
df

['CPU', 'Case', 'Cooler', 'Earphone', 'HDD', 'Headphone', 'Headset', 'Keyboard', 'MBoard', 'Monitor', 'Mouse', 'Power', 'RAM', 'SSD', 'SSD_detail', 'SSD_review', 'Speaker', 'VGA']

,price,제조회사,등록년월,[기본사양]제품분류,[기본사양]폼팩터,[기본사양]인터페이스,[기본사양]용량,[기본사양]메모리 타입,[기본사양]낸드 구조,[기본사양]RAM 유무,...,호환 디스크 타입기타,색상레드,보관(장착) 개수,부가기능제품재질,A/S기간10년,색상오렌지,A/S기간[지원기능],부가기능맥북 업그레이드용,A/S기간6년,지원기능유통회사
id,,,,,,,,,,,,,,,,,,,,,
13190711,549000.0,삼성전자 ( 제조사 웹사이트 바로가기),2021년 01월,내장형SSD,6.4cm(2.5형),SATA3 (6Gb/s),4TB,TLC(기타),3D낸드,DRAM 탑재,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13190630,291600.0,삼성전자 ( 제조사 웹사이트 바로가기),2021년 01월,내장형SSD,6.4cm(2.5형),SATA3 (6Gb/s),2TB,TLC(기타),3D낸드,DRAM 탑재,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13190573,120990.0,삼성전자 ( 제조사 웹사이트 바로가기),2021년 01월,내장형SSD,6.4cm(2.5형),SATA3 (6Gb/s),1TB,TLC(기타),3D낸드,DRAM 탑재,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13190519,58680.0,삼성전자 ( 제조사 웹사이트 바로가기),2021년 01월,내장형SSD,6.4cm(2.5형),SATA3 (6Gb/s),500GB,TLC(기타),3D낸드,DRAM 탑재,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13190384,47470.0,삼성전자 ( 제조사 웹사이트 바로가기),2021년 01월,내장형SSD,6.4cm(2.5형),SATA3 (6Gb/s),250GB,TLC(기타),3D낸드,DRAM 탑재,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1760984,NaN,청연MnS,2012년 08월,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1649117,1700.0,라이트컴 COMS,2012년 04월,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1649110,1700.0,라이트컴 COMS,2012년 04월,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1634506,223600.0,명정보기술,2012년 03월,내장형SSD,6.4cm(2.5형),SATA3(6Gb/s),128GB,MLC(기타),NaN,확인요망,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1187403,390000.0,EKMEMORY,2010년 09월,내장형SSD,NaN,SATA3(6Gb/s),128GB,MLC(기타),NaN,확인요망,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
import pandas as pd
import numpy as np
def get_hdf_keys(dir):
    with pd.HDFStore(dir) as store:
        return [e[1:] for e in store.keys()]

dir = 'compuzone_crawling_data.h5'
print(get_hdf_keys(dir))
df = pd.read_hdf(dir, 'CPU')
df
# df[df['제품분류'] == 'SSD/HDD 주변기기' and df['상세분류'] == '설치 키트']
# df[df['상세분류'] == '설치 키트']
# df[df['good'].isnull()]
# df[~df['색상옐로우'].isnull()]

['CLC', 'CPU', 'Case', 'Cooler', 'DSP', 'HDD', 'MBoard', 'ODD', 'Power', 'RAM', 'SSD', 'VGA']

                                                     name     price
id
893908  [AMD] 라이젠 5 4600G [르누아르] (6코어/12스레드/3.7GHz/쿨러포...  145000.0
867859  [INTEL] 코어12세대 i5-12400F 정품박스 (엘더레이크 /2.50GHz/...  251000.0
728068  [AMD] 라이젠9 버미어 5950X (16코어/32스레드/3.4GHz/쿨러미포함/...  730000.0
730080  [AMD] 라이젠5 버미어 5600X (6코어/12스레드/3.7GHz/쿨러포함/대리...  220000.0
822475  [AMD] 라이젠5 세잔 5600G (6코어/12스레드/3.9GHz/쿨러포함/대리점...  196500.0
...                                                   ...       ...
598384  [INTEL] 코어9세대 i9-9900KF 정품벌크 (커피레이크 리프레시/3.60G...       NaN
818441  [INTEL] 펜티엄 골드 G6605 벌크 동쿨러포함 (코멧레이크S 리프레시/4.3...       NaN
772795  [INTEL] 코어11세대 i9-11900 정품박스 (로켓레이크 /2.50GHz/1...       NaN
598370  [INTEL] 제온 스케일러블 골드 6248 정품(캐스케이드레이크/2.50GHz/2...       NaN
582525  [AMD] 라이젠 5 마티스 3600 (6코어/12스레드/3.6GHz/쿨러포함/대리...       NaN

[362 rows x 2 columns]

In [38]:
import pandas as pd
import numpy as np
def get_hdf_keys(dir):
    with pd.HDFStore(dir) as store:
        return [e[1:] for e in store.keys()]

dir = 'happy_shopping_crawling_data.h5'
print(get_hdf_keys(dir))
df = pd.read_hdf(dir, 'MBoard')
df
# df[df['제품분류'] == 'SSD/HDD 주변기기' and df['상세분류'] == '설치 키트']
# df[df['상세분류'] == '설치 키트']
# df[df['good'].isnull()]
# df[~df['색상옐로우'].isnull()]

['CPU', 'MBoard', 'RAM', 'VGA']

                                                       name     price
id
6260057                                   MSI MAG B550M 박격포  146500.0
10969593                        ASUS PRIME B660M-A D4 STCOM  165000.0
10969621                             MSI MAG B660M 박격포 DDR4  201500.0
6260049                              MSI MAG B550M 박격포 WiFi  156000.0
10117553                          ASUS PRIME H510M-K 인텍앤컴퍼니   77000.0
...                                                     ...       ...
163682                              Arduino 아두이노 우노 R3 (기본)   20000.0
81928                                     ASUS H81M-K STCOM       NaN
11209488                        GIGABYTE B660 GAMING X 제이씨현       NaN
11209487                  GIGABYTE B660 AORUS ELITE D4 제이씨현       NaN
10005863  ASUS ROG STRIX Z490-E GAMING + KO 지포스 RTX 3070...       NaN

[1520 rows x 2 columns]

In [39]:
import pandas as pd
import numpy as np
def get_hdf_keys(dir):
    with pd.HDFStore(dir) as store:
        return [e[1:] for e in store.keys()]

dir = 'happy_shopping_crawling_data.h5'
print(get_hdf_keys(dir))
df = pd.read_hdf(dir, 'MBoard')
df
# df[df['제품분류'] == 'SSD/HDD 주변기기' and df['상세분류'] == '설치 키트']
# df[df['상세분류'] == '설치 키트']
# df[df['good'].isnull()]
# df[~df['색상옐로우'].isnull()]

['CPU', 'MBoard', 'RAM', 'VGA']

                                                       name     price
id
6260057                                   MSI MAG B550M 박격포  146500.0
10969593                        ASUS PRIME B660M-A D4 STCOM  165000.0
10969621                             MSI MAG B660M 박격포 DDR4  201500.0
6260049                              MSI MAG B550M 박격포 WiFi  156000.0
10117553                          ASUS PRIME H510M-K 인텍앤컴퍼니   77000.0
...                                                     ...       ...
163682                              Arduino 아두이노 우노 R3 (기본)   20000.0
81928                                     ASUS H81M-K STCOM       NaN
11209488                        GIGABYTE B660 GAMING X 제이씨현       NaN
11209487                  GIGABYTE B660 AORUS ELITE D4 제이씨현       NaN
10005863  ASUS ROG STRIX Z490-E GAMING + KO 지포스 RTX 3070...       NaN

[1610 rows x 2 columns]

In [90]:
import pandas as pd
import numpy as np
def get_hdf_keys(dir):
    with pd.HDFStore(dir) as store:
        return [e[1:] for e in store.keys()]

dir = 'happy_shopping_crawling_data.h5'
print(get_hdf_keys(dir))
df = pd.read_hdf(dir, 'SSD')
df

['CPU', 'Case', 'Cooler', 'HDD', 'Keyboard', 'MBoard', 'Mouse', 'Power', 'RAM', 'SSD', 'VGA']

                                                       name     price
id
9830418                    SK하이닉스 Gold P31 M.2 NVMe (500GB)   69000.0
9974201                             삼성전자 980 M.2 NVMe (1TB)  113500.0
9830417                      SK하이닉스 Gold P31 M.2 NVMe (1TB)  138500.0
9974202                           삼성전자 980 M.2 NVMe (500GB)   65000.0
11151909                 SK하이닉스 Platinum P41 M.2 NVMe (1TB)  192500.0
...                                                     ...       ...
10843533                                    MG BX3826 하드보관함   26500.0
10843534                                    MG BX3510 하드보관함   26500.0
10839309  Western Digital WD Green SN350 M.2 NVMe 해외구매 (...  140000.0
10819237                     PNY CS2130 M.2 NVMe 해외구매 (1TB)  165000.0
10819236                     PNY CS2130 M.2 NVMe 해외구매 (2TB)  309000.0

[450 rows x 2 columns]

In [11]:
import pandas as pd
import numpy as np
def get_hdf_keys(dir):
    with pd.HDFStore(dir) as store:
        return [e[1:] for e in store.keys()]

dir = 'danawa_crawling_data.h5'
print(get_hdf_keys(dir))
key = 'CPU'
df = pd.read_hdf(dir, key)
df

['CPU', 'CPU_detail', 'Case', 'Cooler', 'Earphone', 'HDD', 'HDD_detail', 'Headphone', 'Headset', 'Keyboard', 'Laptop', 'MBoard', 'MBoard_detail', 'Monitor', 'Mouse', 'Power', 'Power_detail', 'RAM', 'RAM_detail', 'SSD', 'SSD_detail', 'Speaker', 'VGA', 'VGA_detail']

          id_validator
id
12621851          True
12625265          True
15137684          True
13763867          True
12872324          True
...                ...
2322793           True
1220718           True
686573            True
5651804           True
5132495           True

[890 rows x 1 columns]

In [1]:
import pandas as pd
dir = 'happy_shopping_crawling_data.h5'
pd.read_hdf(dir, 'CPU')

                                         name     price
id
7549747    AMD 라이젠5-4세대 5600X (버미어) (멀티팩(정품))  206500.0
10969556     인텔 코어i5-12세대 12400F (엘더레이크) (정품)  230600.0
7421860   AMD 라이젠5 PRO 4650G (르누아르) (멀티팩(정품))  148500.0
10379922    AMD 라이젠5-4세대 5600G (세잔) (멀티팩(정품))  188500.0
10969558     인텔 코어i3-12세대 12100F (엘더레이크) (정품)  125000.0
...                                       ...       ...
5234078      인텔 코어i5-6세대 6500 (스카이레이크) (해외구매)       NaN
1414696     인텔 코어i7-6세대 6700K (스카이레이크) (해외구매)       NaN
1414680             인텔 펜티엄 G3258 (하스웰) (해외구매)       NaN
988955                       AMD 테스트상품 [구매불가]       NaN
9986871        인텔 코어i7-4세대 4770K (하스웰) (해외구매)       NaN

[690 rows x 2 columns]

In [1]:
import pandas as pd
import numpy as np
def get_hdf_keys(dir):
    with pd.HDFStore(dir) as store:
        return [e[1:] for e in store.keys()]

dir = 'test.h5'
print(get_hdf_keys(dir))
df = pd.DataFrame([[2, 3, 2], [1, 4, 2]], columns=list('abc'))
df.set_index('a', inplace=True)
print(df)
with pd.HDFStore(dir) as f:
    f.append('c', df)
    df = pd.DataFrame([[2, 3, 2], [3, 4, 2]], columns=list('abc'))
    df.set_index('a', inplace=True)
    print(df)
    f.append('c', df)
    print(f['c'])

['---', 'L', 'a', 'aaa', 'asd', 'bbb', 'c', 'df', 'gargarg', 'gra', 'k', 'x', 'z']
   b  c
a
2  3  2
1  4  2
   b  c
a
2  3  2
3  4  2
   b  c
a
2  3  2
1  4  2
2  3  2
3  4  2
2  3  2
1  4  2
2  3  2
3  4  2

In [3]:
df = pd.read_hdf(dir, 'c')
df.loc[2]

   b  c
a
2  3  2
2  3  2
2  3  2
2  3  2

In [ ]:
import pandas as pd
import numpy as np
def get_hdf_keys(dir):
    with pd.HDFStore(dir) as store:
        return [e[1:] for e in store.keys()]

dir = 'happy_shopping_crawling_data.h5'

In [77]:
try:
    int("number")
except Exception as e:
    print(e)

invalid literal for int() with base 10: 'number'

In [87]:
from tqdm import tqdm
from time import sleep
for i in tqdm(range(50, 100), initial=50, total=100):
    sleep(1)

 63%|██████▎   | 63/100 [00:14<00:40,  1.09s/it]

KeyboardInterrupt:

In [26]:
import pandas as pd
import numpy as np
def get_hdf_keys(dir):
    with pd.HDFStore(dir) as store:
        return [e[1:] for e in store.keys()]

dir = 'danawa_crawling_data.h5'
print(get_hdf_keys(dir))
df = pd.read_hdf(dir, 'CPU')
print(df.iloc[38].name)
# df[df['제품분류'] == 'SSD/HDD 주변기기' and df['상세분류'] == '설치 키트']
# df[df['상세분류'] == '설치 키트']
# df[df['good'].isnull()]
# df[~df['색상옐로우'].isnull()]

['CPU', 'CPU_detail', 'Case', 'Cooler', 'Earphone', 'HDD', 'HDD_detail', 'Headphone', 'Headset', 'Keyboard', 'Laptop', 'MBoard', 'MBoard_detail', 'Monitor', 'Mouse', 'Power', 'Power_detail', 'RAM', 'RAM_detail', 'SSD', 'SSD_detail', 'Speaker', 'VGA', 'VGA_detail']
16232846

In [112]:
df = pd.DataFrame([[0, 0, np.NaN], [np.NaN, 3.2, 1.5], ['asdf', np.NaN, 'qwer']], columns=list('ABC'))
print(df)
df['A']

      A    B     C
0     0  0.0   NaN
1   NaN  3.2   1.5
2  asdf  NaN  qwer

0       0
1     NaN
2    asdf
Name: A, dtype: object

In [57]:
keys = []
with pd.HDFStore('test.h5') as store:
    keys = [e[1:] for e in store.keys()]
df = pd.read_hdf('test.h5', keys[6])
print(df)

print(df.keys())
print(df.index)

for e in df.index:
    print(df.loc[e])

                  B         C
A
 1.599932 -2.302774 -0.549416
-0.593894  2.244382  0.391734
-1.723089 -0.380325  0.009819
Index(['B', 'C'], dtype='object')
Float64Index([1.5999316453802, -0.5938941821687909, -1.7230889777400156], dtype='float64', name='A')
B   -2.302774
C   -0.549416
Name: 1.5999316453802, dtype: float64
B    2.244382
C    0.391734
Name: -0.5938941821687909, dtype: float64
B   -0.380325
C    0.009819
Name: -1.7230889777400156, dtype: float64

In [98]:
df = pd.DataFrame(np.random.randn(3, 6), columns=pd.MultiIndex.from_product([list('AB'), list('abc')]))
print(df)
df.to_csv('test.csv')
df = pd.read_csv('test.csv', index_col=0)
print('-'*30)
print(df)

          A                             B
          a         b         c         a         b         c
0  0.942282  1.122316 -1.534535 -0.738435  1.219521 -0.660213
1 -1.000766  1.220843  1.799400 -0.158928 -0.331117  0.095575
2 -1.326200  0.369021  0.716628  0.249470 -0.649662 -0.031195
------------------------------
                       A                 A.1                  A.2  \
NaN                    a                   b                    c
0.0   0.9422824331902468  1.1223164034308577  -1.5345352799747125
1.0  -1.0007656784861467   1.220842875477749   1.7994001320259332
2.0  -1.3261995957110504  0.3690211091028248     0.71662764971489

                        B                   B.1                    B.2
NaN                     a                     b                      c
0.0   -0.7384347520470522     1.219521030463626    -0.6602130626888103
1.0  -0.15892763683032923  -0.33111695478969766    0.09557466707600377
2.0   0.24946991039403243   -0.6496623165745024  -0.031195070579843852

In [96]:
df = pd.DataFrame(np.random.randn(3, 3), columns=list('ABC'))
df.set_index('A', inplace=True)
print(df)
df.to_csv('test.csv')
df = pd.read_csv('test.csv', index_col=0)
print(df)

                  B         C
A
-0.176160  1.768536 -2.343992
-0.326147 -1.289444 -0.357165
-0.316305  0.174374  0.110372
                  B         C
A
-0.176160  1.768536 -2.343992
-0.326147 -1.289444 -0.357165
-0.316305  0.174374  0.110372

In [4]:
import logging, sys
logging.basicConfig(stream=sys.stderr, level=logging.ERROR)
logging.debug('A debug message!')
logging.info('We processed %d records', len([32, 2]))

DEBUG:root:A debug message!
INFO:root:We processed 2 records

In [5]:
for i in range(30):
    if i == 20:
        break

print(i)

20